-- Paste this entire file into the Supabase SQL Editor and click Run.
-- This inserts all 26 restaurants into the restaurants table.

INSERT INTO restaurants (id, name, cuisine, price, address, website, instagram, reservation, notes, tags, sources, is_new) VALUES

(1, 'Queensyard', 'Contemporary American', 4, 'Level 4, 20 Hudson Yards', 'https://www.queensyardnyc.com', 'https://www.instagram.com/queensyardnyc/', 'https://resy.com/cities/new-york-ny/venues/queensyard', 'Stunning Vessel views, London-style American. Creative cocktails. Best for when you want to impress.', '{"occasion":["romantic_milestone","saturday_night_out","birthday_dinner","anniversary"],"vibe":["buzzy_lively","grand_impressive","trendy_scene"],"drinks":["craft_cocktails","extensive_wine_list"],"food":["sharing_plates","chef_driven"],"group":["large_group","couples_only_vibe"],"value":["worth_the_splurge"],"dietary":[]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/queensyard"},{"label":"OpenTable","url":"https://www.opentable.com/r/queensyard-new-york"}]', false),

(2, 'Zou Zou''s', 'Eastern Mediterranean', 3, '385 9th Ave, Manhattan West', 'https://www.zouzousnyc.com', 'https://www.instagram.com/zouzousnyc/', 'https://www.opentable.com/r/zou-zous-new-york', 'Perpetually packed after-work crowd. Moodily lit, great sharing plates. Chez Zou upstairs for cocktails.', '{"occasion":["after_work_drinks","saturday_night_out","birthday_dinner"],"vibe":["buzzy_lively","trendy_scene","grand_impressive"],"drinks":["craft_cocktails","destination_bar"],"food":["sharing_plates","chef_driven"],"group":["large_group"],"value":["worth_the_splurge"],"dietary":["vegetarian_friendly"]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/zou-zous"},{"label":"OpenTable","url":"https://www.opentable.com/r/zou-zous-new-york"}]', false),

(3, 'Estiatorio Milos', 'Greek Seafood', 4, 'Level 5, 20 Hudson Yards', 'https://www.estiatoriomilos.com/location/nyhudsonyards/', 'https://www.instagram.com/estiatoriomilos/', 'https://resy.com/cities/new-york-ny/venues/estiatorio-milos-hudson-yards', 'World-renowned Greek seafood. One of the clearest engagement/anniversary choices in the neighborhood. Outdoor terrace overlooking the Yards.', '{"occasion":["romantic_milestone","anniversary","business_dinner"],"vibe":["grand_impressive","intimate_quiet","old_school_classic"],"drinks":["extensive_wine_list"],"food":["traditional_entrees","chef_driven"],"group":["couples_only_vibe"],"value":["corporate_card_only"],"dietary":["gluten_free_friendly"]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/estiatorio-milos-hudson-yards"},{"label":"OpenTable","url":"https://www.opentable.com/r/estiatorio-milos-hudson-yards-new-york"}]', false),

(4, 'Peak with Priceless', 'American', 4, '101st Floor, 30 Hudson Yards', 'https://www.peaknyc.com', 'https://www.instagram.com/peakhudsonyards/', 'https://www.opentable.com/r/peak-restaurant-and-bar-new-york', '101st floor, one above Edge. Free Edge admission with $60 spend. Views are the main event — the food plays second fiddle.', '{"occasion":["birthday_dinner","saturday_night_out","first_date","romantic_milestone"],"vibe":["grand_impressive","buzzy_lively","trendy_scene"],"drinks":["craft_cocktails","extensive_wine_list"],"food":["traditional_entrees","sharing_plates"],"group":["large_group","couples_only_vibe"],"value":["worth_the_splurge"],"dietary":[]}', '[{"label":"OpenTable","url":"https://www.opentable.com/r/peak-restaurant-and-bar-new-york"}]', false),

(5, 'Greywind / Spygold', 'Contemporary American', 3, '451 10th Avenue', 'https://www.greywindnyc.com', 'https://www.instagram.com/greywind_nyc/', 'https://resy.com/cities/new-york-ny/venues/greywind', 'Dan Kluger''s gem. Greywind upstairs, Spygold cocktail bar below. Most neighborhood-feeling spot here. NY Mag best burgers list.', '{"occasion":["first_date","saturday_night_out","after_work_drinks"],"vibe":["cozy","intimate_quiet","hidden_gem","unpretentious"],"drinks":["craft_cocktails","destination_bar"],"food":["sharing_plates","chef_driven"],"group":["couples_only_vibe","solo_friendly"],"value":["worth_the_splurge","happy_hour_deal"],"dietary":["vegetarian_friendly"]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/greywind"},{"label":"Resy","url":"https://blog.resy.com/2023/04/greywind/"}]', false),

(6, 'Electric Lemon', 'New American', 3, '24th Floor, Equinox Hotel, 31 Hudson Yards', 'https://electriclemonnyc.com', 'https://www.instagram.com/electriclemonnyc/', 'https://resy.com/cities/new-york-ny/venues/electric-lemon', 'Seasonal American on the 24th floor of the Equinox Hotel. Rooftop terrace with fire pits. Health-conscious but not boring about it.', '{"occasion":["saturday_night_out","first_date","after_work_drinks"],"vibe":["trendy_scene","buzzy_lively"],"drinks":["craft_cocktails","destination_bar"],"food":["sharing_plates"],"group":["couples_only_vibe","large_group"],"value":["worth_the_splurge"],"dietary":["vegetarian_friendly","gluten_free_friendly"]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/electric-lemon"}]', false),

(7, 'BondST', 'Japanese / Asian-American', 3, 'Level 5, 20 Hudson Yards', 'https://www.bondstrestaurant.com', 'https://www.instagram.com/bondst.hudsonyards/', 'https://www.opentable.com/r/bondst-hudson-yards-new-york', 'Elevated Japanese with a strong cocktail program. 25-year NoHo institution, now with a Hudson Yards home. More relaxed than Katsuya but still impressive.', '{"occasion":["business_dinner","first_date","anniversary","saturday_night_out"],"vibe":["intimate_quiet","trendy_scene"],"drinks":["craft_cocktails","extensive_wine_list"],"food":["sharing_plates","traditional_entrees"],"group":["couples_only_vibe","large_group"],"value":["worth_the_splurge"],"dietary":["gluten_free_friendly"]}', '[{"label":"OpenTable","url":"https://www.opentable.com/r/bondst-hudson-yards-new-york"}]', false),

(8, 'P.J. Clarke''s', 'American Bar & Grill', 2, '4 Hudson Yards', 'https://www.pjclarkes.com/location/hudson-yards', 'https://www.instagram.com/pjclarkes/', null, 'About 50% bar — and it knows it. Best burger in the neighborhood. After-work crowd owns this place 5–7pm weekdays.', '{"occasion":["after_work_drinks","saturday_night_out"],"vibe":["old_school_classic","unpretentious","buzzy_lively"],"drinks":["standard_bar","great_beer_selection"],"food":["bar_snacks_only","traditional_entrees"],"group":["watch_games_with_friends","large_group","solo_friendly"],"value":["great_value"],"dietary":[]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/pj-clarkes-hudson-yards"}]', false),

(10, 'Mercado Little Spain', 'Spanish Market / Hall', 2, '10 Hudson Yards', 'https://www.littlespain.com', 'https://www.instagram.com/mercadolittlespain/', null, 'José Andrés food hall. NY Times: more great food per square foot than anywhere in NYC. Go with a group and try everything.', '{"occasion":["saturday_night_out","sunday_brunch","birthday_dinner"],"vibe":["buzzy_lively","unpretentious"],"drinks":["standard_bar","natural_wine"],"food":["sharing_plates","bar_snacks_only"],"group":["large_group","family_friendly"],"value":["great_value"],"dietary":["vegetarian_friendly"]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/mercado-little-spain"},{"label":"NY Times","url":"https://www.nytimes.com/2019/03/14/dining/mercado-little-spain-review.html"}]', false),

(11, 'La Barra', 'Spanish Tapas', 2, 'Inside Mercado Little Spain, 10 Hudson Yards', 'https://www.littlespain.com', 'https://www.instagram.com/mercadolittlespain/', 'https://www.opentable.com/r/la-barra-new-york', 'Best happy hour in Hudson Yards. Solid tapas, great wine by the glass, zero attitude.', '{"occasion":["after_work_drinks","saturday_night_out"],"vibe":["buzzy_lively","unpretentious"],"drinks":["standard_bar","natural_wine"],"food":["sharing_plates"],"group":["large_group"],"value":["great_value","happy_hour_deal"],"dietary":["vegetarian_friendly"]}', '[{"label":"OpenTable","url":"https://www.opentable.com/r/la-barra-new-york"}]', false),

(12, 'Miznon', 'Israeli Street Food', 1, '10 Hudson Yards', 'https://www.miznon.com/nyc', 'https://www.instagram.com/miznon_usa/', null, 'No-frills Israeli pita counter. Whole-roasted cauliflower pita is a signature. Best quick lunch in the neighborhood.', '{"occasion":["business_lunch","sunday_brunch"],"vibe":["unpretentious","buzzy_lively"],"drinks":["standard_bar"],"food":["bar_snacks_only","sharing_plates"],"group":["solo_friendly","family_friendly"],"value":["great_value","budget_friendly"],"dietary":["vegetarian_friendly"]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/miznon-hudson-yards"},{"label":"Eater NY","url":"https://ny.eater.com/venue/miznon-hudson-yards"}]', false),

(14, 'Bronx Brewery Kitchen', 'Bar / American', 1, 'Level 2, Hudson Yards Shops', 'https://www.thebronxbrewery.com/hudson-yards', 'https://www.instagram.com/bronxbrewery/', null, 'Best spot in the neighborhood to catch a game. Relaxed, no pretense, solid rotating taps.', '{"occasion":["after_work_drinks","saturday_night_out"],"vibe":["unpretentious","cozy"],"drinks":["great_beer_selection","standard_bar"],"food":["bar_snacks_only"],"group":["watch_games_with_friends","large_group","solo_friendly"],"value":["great_value","budget_friendly"],"dietary":[]}', '[{"label":"Hudson Yards","url":"https://www.hudsonyardsnewyork.com/food-drink/bronx-brewery"}]', false),

(15, 'Shake Shack', 'Fast Casual American', 1, 'Hudson Yards', 'https://www.shakeshack.com/location/hudson-yards-nyc/', 'https://www.instagram.com/shakeshack/', null, 'It''s Shake Shack. Reliable, fast, no surprises.', '{"occasion":["business_lunch"],"vibe":["unpretentious"],"drinks":["standard_bar"],"food":["traditional_entrees"],"group":["solo_friendly","family_friendly"],"value":["great_value","budget_friendly"],"dietary":[]}', '[]', false),

(16, 'Limusina', 'Upscale Mexican', 3, '441 9th Avenue', 'https://www.limusina.com', 'https://www.instagram.com/limusinanyc/', 'https://resy.com/cities/new-york-ny/venues/limusina', 'Newest Quality Branded hotspot (Don Angie, Zou Zou''s). 3-level former parking garage. Great drinks and snacks.', '{"occasion":["saturday_night_out","birthday_dinner","first_date","after_work_drinks"],"vibe":["trendy_scene","buzzy_lively","grand_impressive"],"drinks":["craft_cocktails","destination_bar"],"food":["sharing_plates","chef_driven"],"group":["large_group","couples_only_vibe"],"value":["worth_the_splurge"],"dietary":["vegetarian_friendly"]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/limusina"},{"label":"Eater NY","url":"https://ny.eater.com/venue/limusina-nyc"},{"label":"Robb Report","url":"https://robbreport.com/food-drink/dining/limusina-quality-branded-mexican-restaurant-nyc-1237037953/"}]', false),

(17, 'Kyma', 'Greek / Mediterranean Seafood', 3, '445 W 35th Street', 'https://kymarestaurants.com/nyc', 'https://www.instagram.com/kymahudsonyards/', 'https://www.opentable.com/r/kyma-hudson-yards-new-york', 'Whitewashed Mykonos interior. DJ Fridays & Saturdays from 8pm — vibe shifts significantly. Fish flown daily from the Mediterranean.', '{"occasion":["saturday_night_out","anniversary","business_dinner","birthday_dinner"],"vibe":["buzzy_lively","grand_impressive","trendy_scene"],"drinks":["craft_cocktails","extensive_wine_list"],"food":["traditional_entrees","sharing_plates","chef_driven"],"group":["large_group","couples_only_vibe"],"value":["worth_the_splurge"],"dietary":["gluten_free_friendly"]}', '[{"label":"OpenTable","url":"https://www.opentable.com/r/kyma-hudson-yards-new-york"}]', false),

(18, 'NIZUC', 'Contemporary Coastal Mexican', 3, 'Hudson Yards', 'https://www.nizucrestaurant.com', 'https://www.instagram.com/nizucnyc/', 'https://www.opentable.com/r/nizuc-new-york', 'Coastal Mexican with Latin flair. Vibrant atmosphere, quality-ingredient focused.', '{"occasion":["saturday_night_out","first_date","after_work_drinks"],"vibe":["buzzy_lively","trendy_scene"],"drinks":["craft_cocktails"],"food":["sharing_plates","traditional_entrees"],"group":["large_group","couples_only_vibe"],"value":["worth_the_splurge"],"dietary":["vegetarian_friendly"]}', '[{"label":"OpenTable","url":"https://www.opentable.com/r/nizuc-new-york"}]', false),

(19, 'Russ & Daughters', 'Jewish Deli / Appetizing', 2, '50 Hudson Yards', 'https://www.russanddaughters.com/cafe', 'https://www.instagram.com/russanddaughters/', 'https://resy.com/cities/new-york-ny/venues/russ-and-daughters-hudson-yards', '110-year-old LES icon. Smoked fish, bagels, bialys, babka. Caviar & champagne bar opening soon.', '{"occasion":["sunday_brunch","business_lunch"],"vibe":["old_school_classic","unpretentious","hidden_gem"],"drinks":["destination_bar"],"food":["traditional_entrees"],"group":["solo_friendly","family_friendly","couples_only_vibe"],"value":["great_value","worth_the_splurge"],"dietary":["gluten_free_friendly"]}', '[{"label":"Eater NY","url":"https://ny.eater.com/venue/russ-and-daughters-hudson-yards"}]', false),

(20, 'Oyamel', 'Mexican', 2, '10 Hudson Yards', 'https://www.oyamel.com/hudson-yards', 'https://www.instagram.com/oyamelnyc/', 'https://www.opentable.com/r/oyamel-new-york', 'José Andrés'' Mexican concept. Lighter and more casual than Limusina. Good margaritas and antojitos post-work.', '{"occasion":["after_work_drinks","saturday_night_out","sunday_brunch"],"vibe":["buzzy_lively","unpretentious"],"drinks":["craft_cocktails"],"food":["sharing_plates"],"group":["large_group","family_friendly"],"value":["great_value"],"dietary":["vegetarian_friendly"]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/oyamel-hudson-yards"}]', false),

(21, 'ANA Bar and Eatery', 'All-Day Café / American', 2, '15 Hudson Yards', 'https://www.15hudsonyards.com/dining/ana', 'https://www.instagram.com/anabarandeatery/', null, 'All-day café inside 15 Hudson Yards. Good pit stop before or after The Shed.', '{"occasion":["sunday_brunch","business_lunch"],"vibe":["cozy","unpretentious"],"drinks":["standard_bar"],"food":["traditional_entrees","bar_snacks_only"],"group":["solo_friendly","family_friendly"],"value":["great_value"],"dietary":[]}', '[]', false),

(22, 'Eataly', 'Italian Market / Café', 2, 'Hudson Yards', 'https://www.eataly.com/us_en/stores/nyc-hudson-yards/', 'https://www.instagram.com/eataly/', null, 'Fourth NYC Eataly, opened spring 2025. Italian marketplace with pasta, pizza, coffee, and wine.', '{"occasion":["sunday_brunch","business_lunch"],"vibe":["buzzy_lively","unpretentious"],"drinks":["standard_bar","natural_wine"],"food":["traditional_entrees","sharing_plates"],"group":["solo_friendly","family_friendly","large_group"],"value":["great_value"],"dietary":["vegetarian_friendly"]}', '[{"label":"Eater NY","url":"https://ny.eater.com/venue/eataly-hudson-yards"}]', false),

(23, 'Fuku', 'Fast Casual / Fried Chicken', 1, 'Hudson Yards', 'https://www.fuku.com', 'https://www.instagram.com/eatfuku/', null, 'David Chang''s fried chicken concept. Spicy chicken sandwich is the move.', '{"occasion":["business_lunch"],"vibe":["unpretentious"],"drinks":["standard_bar"],"food":["traditional_entrees"],"group":["solo_friendly","family_friendly"],"value":["budget_friendly","great_value"],"dietary":[]}', '[]', false),

(24, 'Ci Siamo', 'Italian / Live-Fire', 3, '440 W 33rd St, Manhattan West', 'https://www.cisiamo.com', 'https://www.instagram.com/cisiamonyc/', 'https://www.sevenrooms.com/reservations/cisiamo/web', 'Danny Meyer / USHG live-fire Italian in Manhattan West. Michelin recognized. Chef Hillary Sterling. Caramelized onion torta alone is worth the trip.', '{"occasion":["romantic_milestone","saturday_night_out","anniversary","business_dinner","first_date"],"vibe":["grand_impressive","intimate_quiet","unpretentious"],"drinks":["craft_cocktails","extensive_wine_list","natural_wine"],"food":["sharing_plates","chef_driven","traditional_entrees"],"group":["couples_only_vibe","large_group"],"value":["worth_the_splurge"],"dietary":["vegetarian_friendly","gluten_free_friendly"]}', '[{"label":"Michelin","url":"https://guide.michelin.com/us/en/new-york-state/new-york/restaurant/ci-siamo"},{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/ci-siamo"},{"label":"Eater NY","url":"https://ny.eater.com/venue/ci-siamo-nyc"}]', false),

(25, 'Papa San', 'Peruvian-Japanese / Nikkei Izakaya', 3, '501 W 34th Street (The Spiral)', 'https://www.papasannyc.com', 'https://www.instagram.com/papasannyc/', 'https://resy.com/cities/new-york-ny/venues/papa-san', 'Opened Feb 2025. Nikkei izakaya: ceviches, robatayaki, eel pizza. Bar by Tres Monos (#7 World''s 50 Best Bars). 60+ sakes.', '{"occasion":["saturday_night_out","first_date","birthday_dinner","after_work_drinks"],"vibe":["buzzy_lively","trendy_scene","hidden_gem"],"drinks":["craft_cocktails","destination_bar","extensive_wine_list"],"food":["sharing_plates","chef_driven"],"group":["large_group","couples_only_vibe","solo_friendly"],"value":["worth_the_splurge"],"dietary":["gluten_free_friendly"]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/papa-san"},{"label":"Michelin","url":"https://guide.michelin.com/us/en/new-york-state/new-york/restaurant/papa-san"},{"label":"Resy","url":"https://blog.resy.com/2025/02/papa-san-nyc/"}]', false),

(26, 'Locanda Verde', 'Italian Osteria', 3, '50 Hudson Yards', 'https://www.locandaverdenyc.com/location/hudson-yards/', 'https://www.instagram.com/locandaverde/', 'https://resy.com/cities/new-york-ny/venues/locanda-verde-hudson-yards', 'Andrew Carmellini''s beloved Tribeca osteria, second location opened 2024. Open breakfast through dinner. Request balcony for intimate seating.', '{"occasion":["romantic_milestone","saturday_night_out","anniversary","business_dinner","sunday_brunch","business_lunch"],"vibe":["grand_impressive","cozy","old_school_classic"],"drinks":["craft_cocktails","extensive_wine_list"],"food":["traditional_entrees","chef_driven","sharing_plates"],"group":["couples_only_vibe","large_group"],"value":["worth_the_splurge"],"dietary":["vegetarian_friendly"]}', '[{"label":"The Infatuation","url":"https://www.theinfatuation.com/new-york/reviews/locanda-verde-hudson-yards"},{"label":"OpenTable","url":"https://www.opentable.com/r/locanda-verde-hudson-yards-new-york"}]', false),

(27, 'Saverne', 'French Brasserie / Alsatian', 3, '531 W 34th St (The Spiral)', 'https://www.savernenyc.com', 'https://www.instagram.com/gabrielkreuther/', 'https://resy.com/cities/new-york-ny/venues/saverne', 'Opened March 2, 2026. Gabriel Kreuther (2 Michelin stars) goes casual. Wood-fired Alsatian brasserie at The Spiral. Tarte flambée, 12-seat chef''s counter. Early buzz is exceptional.', '{"occasion":["saturday_night_out","first_date","business_dinner","romantic_milestone"],"vibe":["grand_impressive","cozy","unpretentious"],"drinks":["craft_cocktails","extensive_wine_list","great_beer_selection"],"food":["sharing_plates","chef_driven","traditional_entrees"],"group":["couples_only_vibe","large_group","solo_friendly"],"value":["worth_the_splurge"],"dietary":["gluten_free_friendly"]}', '[{"label":"Resy","url":"https://blog.resy.com/2026/03/gabriel-kreuther-saverne/"},{"label":"WWD","url":"https://wwd.com/eye/lifestyle/inside-saverne-gabriel-kreuther-restaurant-1238640964/"}]', true),

(28, 'Jajaja Mexicana', 'Plant-Based Mexican', 2, '450 W 33rd St (Manhattan West)', 'https://www.jajajamexicana.com', 'https://www.instagram.com/jajajaplants/', null, '100% plant-based Mexican — the entire menu is vegan by design. House-made tortillas, coco queso, seitan chorizo.', '{"occasion":["business_lunch","saturday_night_out","sunday_brunch","after_work_drinks"],"vibe":["buzzy_lively","unpretentious"],"drinks":["craft_cocktails"],"food":["sharing_plates"],"group":["solo_friendly","family_friendly","large_group"],"value":["great_value"],"dietary":["vegan","vegetarian_friendly","gluten_free_friendly"]}', '[{"label":"Jajaja","url":"https://www.jajajamexicana.com/hudson-yards-ny-ny"}]', false);
